import pimg1 from '/public/images/project/1.jpg';
import pimg2 from '/public/images/project/2.jpg';
import pimg3 from '/public/images/project/3.jpg';
import pimg4 from '/public/images/project/4.jpg';
import pimg5 from '/public/images/project/5.jpg';
import pimg6 from '/public/images/project/6.jpg';

import p2img1 from '/public/images/project-single/1.jpg';
import p2img2 from '/public/images/project-single/2.jpg';
import p2img3 from '/public/images/project-single/3.jpg';
import p2img4 from '/public/images/project-single/4.jpg';
import p2img5 from '/public/images/project-single/5.jpg';
import p2img6 from '/public/images/project-single/6.jpg';

const Projects = [
    {
        id: '1',
        title: 'Heart Surgery Excellence Institute',
        subtitle: 'Cardiovascular Surgery',
        docomunt: 'A fully integrated cardiac surgery program delivering life-saving open-heart and minimally invasive procedures with world-class outcomes.',
        slug: 'Heart-Institute',
        pimg1: pimg1,
        pSimg: p2img1,
        location: 'Medically Cardiac Center, New York, NY',
        client: 'Cleveland Clinic Partnership',
        surgeon: 'Dr. Cody Fisher',
        category: 'Cardiovascular Surgery',
        tags: 'CABG, Valve Repair, Heart Failure',
        date: 'March 2025',
        intro: 'Our Heart Surgery Excellence Program represents a landmark achievement in cardiovascular care. Designed to serve patients with complex and critical cardiac conditions, the program integrates state-of-the-art surgical suites with robotic-assisted cardiac technology, a dedicated cardiac ICU, and a multidisciplinary team of cardiologists, surgeons, anesthesiologists, and rehabilitation specialists.',
        body: 'From its inception, the program has prioritized clinical precision and patient safety. Over 400 open-heart surgeries have been performed since launch, each with outcomes exceeding national benchmarks for survival and complication rates. The program\'s success reflects a culture of continuous improvement, evidence-based practice, and compassionate care.',
        quote: '"The Heart Surgery Excellence Program at Medically gave me a second chance at life. The team\'s precision and support throughout my bypass surgery and recovery was extraordinary."',
        quoteAuthor: 'James Carroll',
        quoteRole: 'CABG Patient',
        strategiesIntro: 'Our cardiac surgery strategy is built around three core pillars: surgical precision, rapid recovery, and long-term cardiac wellness.',
        strategies: [
            'Robotic-assisted and minimally invasive cardiac surgical techniques.',
            'Real-time intraoperative imaging and hemodynamic monitoring.',
            'Dedicated post-cardiac ICU care with 1:1 nursing ratios.',
            'Structured cardiac rehabilitation programs beginning within 48 hours of surgery.',
        ],
        approach: 'We take a multidisciplinary approach to every cardiac case. Pre-operative conferences involve the full surgical, anesthesiology, and critical care team. Intraoperatively, we employ the latest monitoring technologies to ensure precision. Post-operatively, our cardiac rehabilitation team begins structured recovery protocols early to minimize complications and restore full cardiac function as rapidly as possible.',
        goalsIntro: 'The program has consistently exceeded its clinical and operational targets:',
        goals: [
            '98.7% in-hospital survival rate across all cardiac surgical procedures.',
            '40% reduction in post-operative length of stay compared to national average.',
            'Zero central-line associated infections in the cardiac ICU since program launch.',
            'Patient satisfaction scores in the 99th percentile nationally.',
        ],
        resultsIntro: 'The impact of the Heart Surgery Excellence Program extends beyond surgical outcomes:',
        results: [
            'Designated as a Regional Cardiac Surgery Center of Excellence.',
            'Performed the first robotic mitral valve repair in the tri-state area.',
            'Published 8 peer-reviewed outcomes studies in major cardiovascular journals.',
            'Trained 12 early-career cardiac surgeons through a structured fellowship.',
        ],
    },
    {
        id: '2',
        title: 'Advanced Orthopedic Reconstruction',
        subtitle: 'Orthopedic Surgery',
        docomunt: 'A comprehensive orthopedic program specializing in joint replacement, sports medicine, and complex musculoskeletal reconstruction.',
        slug: 'Advanced-Orthopedic-Reconstruction',
        pimg1: pimg2,
        pSimg: p2img2,
        location: 'Medically Orthopedic Center, New York, NY',
        client: 'Hospital for Special Surgery Affiliation',
        surgeon: 'Dr. Jerome Bell',
        category: 'Orthopedic Surgery',
        tags: 'Joint Replacement, Sports Medicine, Spine',
        date: 'January 2025',
        intro: 'The Advanced Orthopedic Reconstruction Program was established to provide the region\'s most technically demanding orthopedic procedures under one roof. Featuring a dedicated robotics suite for joint replacement, an arthroscopic sports medicine theater, and a specialized spine surgery unit, the program serves patients ranging from elite athletes to seniors with degenerative joint disease.',
        body: 'With board-certified orthopedic surgeons performing over 600 procedures annually, the program has become the benchmark for musculoskeletal care in the region. Our approach combines minimally invasive surgical techniques with a robust pre- and post-operative rehabilitation pathway, ensuring patients return to full function in the shortest possible time.',
        quote: '"After my total knee replacement at Medically, I was back on the tennis court in 8 weeks. The surgical team and physios were outstanding at every step."',
        quoteAuthor: 'Sandra Mitchell',
        quoteRole: 'Total Knee Replacement Patient',
        strategiesIntro: 'Our orthopedic program strategy focuses on innovation, precision, and accelerated recovery.',
        strategies: [
            'Robotic-assisted joint replacement for sub-millimeter implant precision.',
            'Same-day or next-day discharge protocols for eligible joint replacement patients.',
            'Sports medicine arthroscopic procedures with same-week scheduling.',
            'Comprehensive pre-operative optimization including physiotherapy and nutrition.',
        ],
        approach: 'Every patient undergoes a thorough pre-operative assessment by our orthopedic team, including advanced imaging, biomechanical analysis, and medical optimization. Surgery is performed with cutting-edge robotic or arthroscopic tools, minimizing tissue disruption. Our dedicated physiotherapy team begins rehabilitation protocols within hours of surgery, dramatically accelerating recovery timelines.',
        goalsIntro: 'The Orthopedic Reconstruction Program has achieved measurable, significant outcomes:',
        goals: [
            '96% patient-reported satisfaction with surgical outcomes at 6-month follow-up.',
            'Average return-to-work time reduced by 35% versus national standard.',
            'Infection rate below 0.3%  — among the lowest nationally.',
            'Robotic-assisted procedures now account for 78% of all joint replacements.',
        ],
        resultsIntro: 'The program has set new standards for orthopedic excellence:',
        results: [
            'Recognized as a Blue Distinction Center for Knee and Hip Replacement.',
            'Partnered with three professional sports organizations as official orthopedic provider.',
            'Implemented a same-day joint replacement pilot reducing hospital costs by 25%.',
            'Expanded spine surgery unit to include full spinal deformity and revision capabilities.',
        ],
    },
    {
        id: '3',
        title: 'Women\'s Gynecological Health Initiative',
        subtitle: 'Gynecology & Women\'s Health',
        docomunt: "A comprehensive women's health program offering minimally invasive gynecologic surgery, fertility services, and preventive care.",
        slug: 'Womens-Gynecological-Health',
        pimg1: pimg3,
        pSimg: p2img3,
        location: 'Medically Women\'s Health Center, New York, NY',
        client: 'Mayo Clinic Women\'s Health Partnership',
        surgeon: 'Dr. Leslie Alexander',
        category: 'Gynecology & Women\'s Health',
        tags: 'Minimally Invasive Surgery, Fertility, Preventive Care',
        date: 'February 2025',
        intro: "The Women's Gynecological Health Initiative was launched to provide New York's women with access to world-class gynecological care in a compassionate, privacy-focused environment. The program spans preventive wellness, complex minimally invasive surgery, fertility evaluation, and menopause management — all under one dedicated team.",
        body: "Operating from a purpose-built women's health suite equipped with the latest laparoscopic and robotic surgical systems, our gynecology team has treated over 1,200 patients in the program's first year. Our holistic approach addresses not just physical symptoms but also the emotional and quality-of-life dimensions of women's health.",
        quote: '"Dr. Alexander and her team handled my endometriosis surgery with extraordinary care and skill. I\'m now pain-free and finally able to focus on starting my family."',
        quoteAuthor: 'Maria Torres',
        quoteRole: 'Endometriosis Surgery Patient',
        strategiesIntro: "Our women's health strategy is centered on minimally invasive excellence and patient empowerment.",
        strategies: [
            'Robotic and laparoscopic procedures for fibroids, endometriosis, and ovarian cysts.',
            'Comprehensive fertility evaluations and referral pathways.',
            'Structured menopause management clinics with hormone therapy options.',
            'Community outreach cervical and breast cancer screening programs.',
        ],
        approach: "We believe every woman deserves to be an informed, empowered participant in her own healthcare. Our gynecologists invest time in comprehensive consultations, clearly explaining all diagnosis, treatment options, and expected outcomes. Surgical procedures are performed with the utmost precision using minimally invasive techniques, resulting in reduced pain, shorter hospital stays, and faster recovery.",
        goalsIntro: "The Women's Gynecological Health Initiative has achieved strong clinical and community impact:",
        goals: [
            '94% reduction in post-operative pain scores versus open surgical comparators.',
            'Average hospital stay of less than 23 hours for laparoscopic procedures.',
            '3,000+ women screened through community cervical cancer prevention programs.',
            'Zero conversions to open surgery in robotic gynecologic cases this year.',
        ],
        resultsIntro: "The program has established itself as the regional leader in women's gynecological care:",
        results: [
            'Accredited as a Center of Excellence in Minimally Invasive Gynecologic Surgery (COEMIGS).',
            'Launched a dedicated endometriosis multidisciplinary clinic — first in the region.',
            'Expanded fertility services with on-site embryology lab and IVF coordination.',
            "Published research on robotic hysterectomy outcomes in the Journal of Minimally Invasive Gynecology.",
        ],
    },
    {
        id: '4',
        title: 'Integrated Rehabilitation Recovery Program',
        subtitle: 'Rehabilitation Medicine',
        docomunt: 'A state-of-the-art rehabilitation program restoring function and independence for patients after surgery, stroke, and serious injury.',
        slug: 'Integrated-Rehabilitation-Recovery',
        pimg1: pimg4,
        pSimg: p2img4,
        location: 'Medically Rehabilitation Center, Chicago, IL',
        client: 'Shirley Ryan AbilityLab Partnership',
        surgeon: 'Dr. Alexander Leslie',
        category: 'Physical Medicine & Rehabilitation',
        tags: 'Neurological Rehab, Post-Surgical, Stroke Recovery',
        date: 'November 2024',
        intro: 'The Integrated Rehabilitation Recovery Program was designed to serve patients with the most complex rehabilitation needs. Combining neurological, orthopedic, and cardiopulmonary rehabilitation under one specialist-led team, the program provides intensive, individualized recovery pathways using the most advanced rehabilitation science and assistive technologies available today.',
        body: 'Housed in a purpose-built 30,000 sq ft rehabilitation facility, the program offers inpatient, outpatient, and day rehabilitation services. Every patient receives a customized recovery plan developed by a multidisciplinary team of physiatrists, physiotherapists, occupational therapists, speech-language pathologists, and clinical psychologists working in close coordination.',
        quote: '"After my stroke, I didn\'t know if I\'d ever walk or speak clearly again. The rehabilitation team at Medically restored my independence in ways I never thought possible."',
        quoteAuthor: 'Frank Okafor',
        quoteRole: 'Stroke Rehabilitation Patient',
        strategiesIntro: 'Our rehabilitation strategy integrates evidence-based therapy with emerging assistive technology.',
        strategies: [
            'Neuroplasticity-focused therapy protocols for stroke and brain injury recovery.',
            'Robotic exoskeleton-assisted gait training for spinal cord and neurological patients.',
            'Intensive speech and language therapy for post-stroke communication recovery.',
            'Virtual reality-based motor retraining and cognitive rehabilitation modules.',
        ],
        approach: 'We begin rehabilitation planning from the moment a patient is medically stable. Our interdisciplinary team conducts daily rounds to review progress, adjust therapy intensity, and align goals with the patient and their family. By setting clear, measurable functional milestones and providing transparent progress updates, we keep patients motivated and families informed throughout the recovery journey.',
        goalsIntro: 'The Integrated Rehabilitation Recovery Program has delivered outstanding patient outcomes:',
        goals: [
            '87% of stroke patients achieved independent ambulation within the program.',
            'Average functional independence measure (FIM) gain of 38 points per admission.',
            '95% of patients discharged to home rather than long-term care facilities.',
            'Speech therapy success rate of 91% for aphasia recovery at 90-day follow-up.',
        ],
        resultsIntro: 'The program has earned national recognition and transformed thousands of lives:',
        results: [
            'Ranked among the Top 10 Rehabilitation Programs in the United States.',
            'First facility in the Midwest to deploy full robotic exoskeleton gait training.',
            'Established a caregiver training academy to support home recovery success.',
            'Published landmark research on VR-assisted neurorehabilitation in stroke patients.',
        ],
    },
    {
        id: '5',
        title: 'Clinical Pharmacology Optimization Project',
        subtitle: 'Pharmacology',
        docomunt: 'A hospital-wide medication safety and optimization initiative delivering safer, more effective drug therapy for all patients.',
        slug: 'Clinical-Pharmacology-Optimization',
        pimg1: pimg5,
        pSimg: p2img5,
        location: 'Medically Pharmacy & Clinical Sciences, Baltimore, MD',
        client: 'Johns Hopkins Medical Center Partnership',
        surgeon: 'Dr. Dianne Russell',
        category: 'Clinical Pharmacology',
        tags: 'Medication Safety, Polypharmacy, Pharmacogenomics',
        date: 'October 2024',
        intro: 'The Clinical Pharmacology Optimization Project is a hospital-wide initiative to transform medication management across all departments. Led by Dr. Dianne Russell and a team of clinical pharmacologists, the project addressed polypharmacy risks, optimized antibiotic stewardship, and introduced pharmacogenomics-guided prescribing — dramatically improving safety and therapeutic outcomes.',
        body: 'Prior to the project, adverse drug events were identified as a key driver of extended hospital stays and readmissions. Through systematic medication therapy management reviews, drug interaction screening, and tailored patient education, the team reduced harmful drug events by 41% in the first year. The project has since been adopted as a model for hospital systems across the region.',
        quote: '"Managing multiple chronic conditions meant I was on 11 different medications. The pharmacology team at Medically reviewed everything and my quality of life has improved enormously."',
        quoteAuthor: 'Dorothy Chen',
        quoteRole: 'Medication Therapy Management Patient',
        strategiesIntro: 'Our pharmacology optimization strategy targets the root causes of medication-related harm.',
        strategies: [
            'Comprehensive polypharmacy reviews for all patients on 5+ concurrent medications.',
            'Clinical pharmacist embedding in oncology, cardiology, and geriatric wards.',
            'Pharmacogenomics screening to personalize drug selection and dosing.',
            'Hospital-wide antibiotic stewardship program to reduce resistance.',
        ],
        approach: 'Our pharmacologists work as integrated members of every clinical care team, attending ward rounds, reviewing prescriptions in real-time, and flagging high-risk drug combinations before they reach the patient. A dedicated compounding pharmacy prepares customized formulations for patients with complex or rare medication needs, ensuring precision dosing and improved tolerability.',
        goalsIntro: 'The Clinical Pharmacology Optimization Project has delivered measurable patient safety improvements:',
        goals: [
            '41% reduction in adverse drug events hospital-wide in the first 12 months.',
            'Antibiotic resistance rates reduced by 28% following stewardship implementation.',
            '100% of high-risk patients received pharmacogenomics-guided therapy review.',
            'Medication-related readmissions reduced by 33% year-over-year.',
        ],
        resultsIntro: 'The project has been recognized as a national model for clinical pharmacy excellence:',
        results: [
            'Awarded the ASHP Best Practice Award for Medication Safety Innovation.',
            'Pharmacogenomics program expanded to all oncology patients hospital-wide.',
            'Published 5 studies on polypharmacy reduction outcomes in peer-reviewed journals.',
            'Program replicated by 6 regional hospital systems following publication of results.',
        ],
    },
    {
        id: '6',
        title: 'Comprehensive Dental Care Modernization',
        subtitle: 'Dental Care',
        docomunt: 'A full modernization of dental care services introducing digital dentistry, cosmetic excellence, and community oral health programs.',
        slug: 'Dental-Care-Modernization',
        pimg1: pimg6,
        pSimg: p2img6,
        location: 'Medically Dental Excellence Center, New York, NY',
        client: 'Columbia University College of Dental Medicine',
        surgeon: 'Dr. Marlene Henry',
        category: 'Dental Care',
        tags: 'Digital Dentistry, Cosmetic, Preventive Care',
        date: 'September 2024',
        intro: "The Comprehensive Dental Care Modernization project transformed Medically's dental department from a traditional practice into a fully digital, patient-centered oral health center. New technologies including 3D cone beam CT imaging, digital impressions, same-day ceramic restorations, and laser dentistry were introduced, resulting in dramatically shorter appointments, improved precision, and superior patient comfort.",
        body: 'The modernization covered a full renovation of the dental suite, introduction of advanced technology platforms, retraining of all clinical staff, and launch of a community oral health outreach program. Since completion, patient volume has grown by 60%, cosmetic dentistry referrals have tripled, and the department has received accreditation as a Center of Excellence in Digital Dentistry.',
        quote: '"I used to dread dental visits. Dr. Henry\'s team made my smile transformation painless, fast, and the results are beyond what I imagined. I actually look forward to my check-ups now."',
        quoteAuthor: 'Angela Brooks',
        quoteRole: 'Cosmetic Dentistry Patient',
        strategiesIntro: 'Our dental modernization strategy centered on technology adoption, patient experience, and community impact.',
        strategies: [
            'Full digital workflow implementation: 3D scanning, CBCT, and CAD/CAM same-day restorations.',
            'Introduction of laser dentistry for soft tissue procedures and cavity treatment.',
            'Anxiety management protocols including sedation dentistry for nervous patients.',
            'Community school oral health screening and fluoride treatment programs.',
        ],
        approach: "Our approach to dental modernization prioritized staff development alongside technology installation. Every dentist and dental hygienist received comprehensive training on new digital platforms. Patient communication systems were upgraded so patients receive digital X-ray comparisons, 3D visualizations of proposed cosmetic changes, and post-treatment home care instructions — all digitally, before leaving the chair.",
        goalsIntro: 'The Dental Care Modernization project has transformed oral health delivery:',
        goals: [
            '60% increase in patient volume within 6 months of modernization completion.',
            'Average appointment duration reduced by 30% through digital workflow efficiency.',
            '2,500 children screened and treated through the school oral health program.',
            'Patient anxiety scores reduced by 55% following sedation dentistry introduction.',
        ],
        resultsIntro: 'The modernized dental department has become a regional reference point for digital dentistry:',
        results: [
            'Accredited as a Center of Excellence in Digital Dentistry by the ADA.',
            'Cosmetic dentistry revenue increased by 180% year-over-year.',
            'Launched the first fully paperless dental practice in the New York metro area.',
            'Featured as a case study in the Journal of Digital Dentistry for technology integration.',
        ],
    },
];

export default Projects;
